name: Joe Contini
description: "Things that I find interesting or useful"
url: https://jcontini.github.io
rss: https://jcontini.github.io/feed.xml
github: https://github.com/jcontini/
twitter: https://twitter.com/jcontini
foursquare: https://foursquare.com/jcontini
instagram: http://instagram.com/jcontini/
linkedin: https://linkedin.com/in/jcontini
email: joe@contini.co
disqus: jcontini
baseurl: 

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"