name: Joe Contini
description: "Joe's Adventures"
url: https://jcontini.github.io
github: https://github.com/jcontini/
twitter: https://twitter.com/jcontini
foursquare: https://foursquare.com/jcontini
instagram: http://instagram.com/jcontini/
linkedin: https://linkedin.com/in/jcontini
email: hi@joecontini.com
disqus: diqus-username
baseurl: 

##Make sure to edit the above fields, especially for disqus.

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"